name: Python build

on:
  push:
    paths:
      - '.github/**'
      - 'python/**'
      - 'src/**'
      - 'CMakeLists.txt'
      - 'setup.py'

jobs:
  build:
    strategy:
      matrix:
        #os: [ ubuntu-20.04, ubuntu-18.04, macos-11.0, macos-10.15, windows-latest]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }} environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: GCC version report
      run: gcc --version

    - name: CMake version report
      run: cmake --version

    - name: Python environment report
      run: python -c "import sys; print(sys.version)"

    - name: Pip install
      run: pip install .
