name: Build Windows Python wheels

on:
  push:
    paths:
      - '.github/**'
      - 'python/**'
      - 'src/**'
      - 'CMakeLists.txt'
      - 'setup.py'

jobs:
  deploy:
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Python environment report
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine flake8 cmaketools setuptools wheel

      - name: Lint with flake8 for syntax errors
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Build Windows Python wheels
        run: python setup.py bdist_wheel #-w ./dist --no-deps

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-${{ matrix.python-version }}-dist
          path: dist

    #- name: Publish wheels to PyPI
    #  env:
    #    TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
    #    TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
    #  run: |
    #    twine upload dist/*-win*.whl
